- name: Install MySQL Libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    executable: pip3.9
  loop:
  - cryptography
  - PyMySQL

- name: disable current NodeJs
  ansible.builtin.command: 
    dnf module disable nodejs -y

- name: enabling NodeJs version 20
  ansible.builtin.command:
    dnf module enable nodejs:20 -y

- name: install NodeJs
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
  - nodejs
  - mysql

- name: create expense user
  ansible.builtin.user:
    name: expense

- name: import a role
  ansible.builtin.import_role:
   name: common
   tasks_from: main
# - name: create a directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: download backend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip

# - name: unzip the code
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip
#     dest: /app
#     remote_src: yes

- name: Install dependencies
  community.general.npm:
    path: /app

- name: copy backend service file
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: import mysql data
  community.mysql.mysql_db:
    state: import
    name: all
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql.daws-82s.site
    target: /app/schema/backend.sql

- name: Daemon reload and Restart service
  ansible.builtin.systemd_service:
    enabled: true
    state: restarted
    daemon_reload: true
    name: backend